### ISSUE TITLE
Create a test service context and test product in the staging environment

### ISSUE THREAD

**Issue by erlendoksvoll** [data-altinn-no/core#84]
### Description

We need to create a self-service test setup for new potential consumers of data from DAN in order for them to test the solution  from a developer/technical standpoint

### Tasks

- [ ] New service context "DAN-test"
- [ ] New apim product (only in staging and dev) - DAN-test, with automatic subscription approval
- [ ] New scope in test-maskinporten (dan:test), public and available for everyone
- [ ] New dataset "DAN-test" in the digdir plugin that returns something
- [ ] Explain how this is used under [testing](https://docs.data.altinn.no/testing/)
